### PR TITLE
Add footnote support

### PR DESCRIPTION
**Pull request by michael**

### CODE REVIEW

**Comment by michael** [comment]
Work in progress...

**Comment by michael** [comment]
Ok first implementation is pushed to lens#footnote-support.

Checkout the footnote-support branch on AMS-Lens, and npm install to test.

For each `<fn>` occurence we provide a toggle to show/hide it. Additionally, each `<xref>` will also be able to expand the footnote content inline.

Try to not have `<fn>` and `<xrefs>` close to each other, as you will get the label rendered twice. E.g. in bproc14: Just remove that xref there.

image

Issues:

There are occurences where an xref states ref-type='fn' but links to a section. You should fix this in the XML. See bproc14:

image

**Comment by pkra** [comment]
> For each <fn> occurence we provide a toggle to show/hide it. 

I don't understand why you would want this. A footnote should be hidden until toggled via a reference.

**Comment by pkra** [comment]
> Just remove that xref there.

That seems like bad advice. Footnotes can be moved, references not so much.

**Comment by obuchtala** [comment]
@pkra we found that for footnotes a local presentation is most natural, as they are scoped. Not like citations which are document-wide references, footnotes could be defined in various smaller scopes, such as tables.
Please feel free to try this out...

**Comment by obuchtala** [comment]
> That seems like bad advice. Footnotes can be moved, references not so much.

There are two patterns how to use footnotes. If you prefer `<xrefs>` then please also use `<fn-groups>`  as suggested in http://jats.nlm.nih.gov/archiving/tag-library/1.1/element/fn.html

**Comment by obuchtala** [comment]
This is how footnotes look like currently:
demo-footnotes

**Comment by pkra** [comment]
> @pkra we found that for footnotes a local presentation is most natural, as they are scoped. Not like citations which are document-wide references, footnotes could be defined in various smaller scopes, such as tables.

That's unfortunately not always true.

> There are two patterns how to use footnotes. If you prefer <xrefs> then please also use <fn-groups> 

It would have been nice to discuss this beforehand.

**Comment by obuchtala** [comment]
> > @pkra we found that for footnotes a local presentation is most natural, as they are scoped. Not like citations which are document-wide references, footnotes could be defined in various smaller scopes, such as tables.
> 
> That's unfortunately not always true.

Could you be more specific?

> > There are two patterns how to use footnotes. If you prefer <xrefs> then please also use <fn-groups> 
> 
> It would have been nice to discuss this beforehand.

That's how JATS is actually specified.

**Comment by pkra** [comment]
> Could you be more specific?

The same footnote can be referenced multiple times in a document.

> That's how JATS is actually specified.

AFAIK JATS does not specify rendering. Your rendering choice now forces a certain style of JATS markup.

**Comment by obuchtala** [comment]
> The same footnote can be referenced multiple times in a document.

True. That's fine, as we still have distinguished the concept of ref and content.
It's just that we render the content in place when expanded.

> AFAIK JATS does not specify rendering. Your rendering choice now forces a certain style of JATS markup.

Don't know how you come to that conclusion.
JATS gives advice to follow the best practice to use `<fn-group>` in combination with `<xref>`
Looking at the specification of `<fn>` alone, it is essentially similar to an inline node.
Thus, I see the two different possible ways to use it.

Edit: the same way as whitespace is relevant in XML, an placed inline-node should be relevant, too.

**Comment by michael** [comment]
We would have the option of just rendering fn xrefs. But then all unreferenced footnotes wouldn't be accessible. Showing a reference per footnote was our way to solve that. It's a first solution and hope it's going into the right direction. Do you like the inline rendering approach for footnotes generally? I had a quite good feeling about it, compared to popup solutions or displaying them in the side panel. We can certainly iterate on it, it's just we have very little resources available atm. In week of May 9th we can maybe squeeze in some time for footnotes or other remaining issues.

**Comment by davidmjones** [comment]
Our main disagreement is here:

> use one of the following patterns:
> 1. either use `<fn-groups>` + `<xref ref-type=“fn”>`
> 2. or just `<fn>` as an inline element":

and

> There are two patterns how to use footnotes. If you prefer `<xrefs>` then please also use `<fn-groups>`  as suggested in http://jats.nlm.nih.gov/archiving/tag-library/1.1/element/fn.html

That's a misreading of the spec.  What the "Best Practice" section says is

> When footnotes are grouped at the end of an article, wrap them in a `<fn-group>` and use an `<xref>` element in the text, as usual, to tie each footnote in the list to a particular location in the text.

The second paragraph of the "Remarks" page makes it clear what "at the end of an article" means:

> In print, footnotes are traditionally displayed at the bottom of a printed page or in a list at the end of the article (`<fn-group>`);

In other words, `<fn>` is used for both genuine _foot_notes (which appear at the foot of the page) and for _end_notes, which appear collected at the end of an article.  In the latter case, the collected notes should be surrounded by a `<fn-group>`.  The last paragraph under "Remarks" applies to both kinds of notes:

> A reference to a `<fn>` is made with the `<xref>` element.

In our papers, the footnotes are genuine footnotes, so `<fn-group>` is not appropriate.

Other issues:

1) `<xref>` to a section with ref-type="fn" (bproc14): An obvious bug in texml that has been fixed now.

2) XML elements inside `<tex-math>` (btran7): Peter and I have discussed a plan for handling these which we're working on.

3) "Try to not have `<fn>` and `<xrefs>` close to each other, as you will get the label rendered twice."

   Surely it would be easier to just not render the `<fn>` `<label>`?

4) "don’t use `<fn>` as block-level node, such as `<p>`…`</p>``<fn>`..`</fn>``<p>`…`</p>`"

   I only see one example of this, and it's for a footnote attached to a table cell in bproc15.  Everything that could go wrong here did, starting with the author's coding.  I'll try to sort something out.

5) "But then all unreferenced footnotes wouldn't be accessible."

   Just a point of clarification: Strictly speaking, there's no such thing as an unreferenced footnote.  You're probably thinking about something like the info at the bottom of the first page of the PDF versions of the articles: received dates, MSC numbers, key words, funding info, etc., but those aren't translated into `<fn>` elements. They're metadata elements that are marked up differently in the LaTeX code and translated into appropriate elements in the XML code so they can be displayed in the info panel.

I think that's everything.  Let me know if I missed anything.

**Comment by pkra** [comment]
@michael wrote

> Do you like the inline rendering approach for footnotes generally? 

Davide and I both think it fits well with the rest of the design and will be sufficient for now. The smaller size makes them even harder to target than the other types of references but that's a more general problem for another time.

**Comment by pkra** [comment]
Closing this since we only need the change to package.json.

**Pull request closed without merging**
